# sam build && sam deploy --config-env stag
# or
# sam build && sam deploy --config-env prod

version = 0.1

[stag.deploy.parameters]
profile = "prx-feed-cdn-staging"
stack_name = "cdn-publicfeeds-staging"
s3_prefix = "cdn-publicfeeds-staging"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
resolve_s3 = true

[prod.deploy.parameters]
profile = "prx-feed-cdn-production"
stack_name = "cdn-publicfeeds-production"
s3_prefix = "cdn-publicfeeds-production"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
resolve_s3 = true
