# sam build && sam deploy --config-env us-east-1 && sam deploy --config-env us-west-2

version = 0.1

[us-east-1.deploy.parameters]
profile = "prx-legacy"
stack_name = "infrastructure-ci"
s3_prefix = "infrastructure-ci"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kyq6davxwatj"

[us-west-2.deploy.parameters]
profile = "prx-legacy"
stack_name = "infrastructure-ci"
s3_prefix = "infrastructure-ci"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
region = "us-west-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-th1k22gzgt3q"
