# devops/aws-management/organization-alarms-bus.yml

AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Creates a EventBridge rule that forwards all CloudWatch Alarms state change
  events to the DevOps alarms bus. The DevOps event bus must be in a region
  that supports cross-region EventBridge rules.

Parameters:
  DevOpsCloudWatchAlarmsBusArn:
    Type: String

Resources:
  EventRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: events:PutEvents
                Effect: Allow
                Resource: !Ref DevOpsCloudWatchAlarmsBusArn
            Version: "2012-10-17"
          PolicyName: CloudWatchAlarmsBusPolicy
      Tags:
        - { Key: prx:meta:tagging-version, Value: "2021-04-07" }
        - { Key: prx:cloudformation:stack-name, Value: !Ref AWS::StackName }
        - { Key: prx:cloudformation:stack-id, Value: !Ref AWS::StackId }
        - { Key: prx:ops:environment, Value: Production }
        - { Key: prx:dev:application, Value: DevOps }
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        detail-type:
          - CloudWatch Alarm State Change
        source:
          - aws.cloudwatch
      State: ENABLED
      Targets:
        - Arn: !Ref DevOpsCloudWatchAlarmsBusArn
          Id: devops-cloudwatch-alarms-event-bus-fwd
          RoleArn: !GetAtt EventRuleRole.Arn
